export const restsArray = [
  {
    id: 1,
    title: 'Пицца плюс',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest1.jpg',
    alt: 'rest1',
  },
  {
    id: 2,
    title: 'Тануки',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest2.jpg',
    alt: 'rest2',
  },
  {
    id: 3,
    title: 'FoodBand',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest3.jpg',
    alt: 'rest3',
  },
  {
    id: 4,
    title: 'Жадина-пицца',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest4.jpg',
    alt: 'rest4',
  },
  {
    id: 5,
    title: 'Точка еды',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest5.jpg',
    alt: 'rest5',
  },
  {
    id: 6,
    title: 'PizzaBurger',
    time: 50,
    rating: 4.5,
    price: 900,
    type: 'Пицца',
    image: 'rest6.jpg',
    alt: 'rest6',
  },
];
